const system_settings = {
  SUBSCRIPTION_FREE_TRIAL: 14,
  DEFAULT_PACKAGE: 'GROWTH',
  MINIMAL_PACKAGE: 'MINIMAL',
  EXT_FREE_PACKAGE: 'EXT_FREE',
  EXT_PACKAGE: 'EXT',
  EMAIL_ONE_TIME: 15,
  EMAIL_DAILY_LIMIT: {
    BASIC: 500,
    GMAIL: 500,
    GSUIT: 1500,
    OUTLOOK: 300,
    MICROSOFT: 2000,
  },
  TEXT_ONE_TIME: 10,
  PASSWORD: {
    USER: process.env.DEFAULT_PASS,
    ADMIN: process.env.ADMIN_DEFAULT_PASS,
  },
  COMPANY: {
    DEFAULT: 'eXp Realty',
  },
  ADMIN_ACCOUNT: 'support@crmgrow.com',
  ONBOARD_ACCOUNT: 'hello@crmgrow.com',
  ONBOARD_AUTOMATION: '631a44142815af0014914e26',
  DATA_RELEASE_RETENTION: 15,
  DATA_RETENTION: 60,
  LEAD: '5f16d58d0af09220208b6e11',
  AUTO_FOLLOW_UP: 'has reviewed material',
  AUTO_FOLLOW_UP2: 'didn`t watch material',
  THUMBNAIL: {
    WIDTH: 400,
    HEIGHT: 220,
  },
  IMAP_PORT: 587,
  ONBOARD_PRICING_30_MINS: 5000,
  ONBOARD_PRICING_1_HOUR: 4900,
  TWILIO_EXCHANGE_NUMBER: 1000,
  SCHEDULE_LINK_30_MINS: 'https://calendly.com/coachwithdaniel/crm-grow-30',
  SCHEDULE_LINK_1_HOUR:
    'https://calendly.com/support-1196/crmgrow-1-hour-session',
  CAMPAIGN_MAIL_START: {
    SMTP: 500,
    GMAIL: 150,
    GSUIT: 500,
    OUTLOOK: 150,
    MICROSOFT: 500,
    AWS: 5000,
  },
  LABEL_LIMIT: 50,
  CAMPAIGN_MAIL_LIMIT: {
    GMAIL: 400,
    GSUIT: 1500,
    OUTLOOK: 250,
    MICROSOFT: 1000,
    AWS: 5000,
  },
  DEMO_VIDEO: '60ad6077af664b0016ebb176',
  WEBINAR_LINK: 'https://calendly.com/support-1196/crmgrow-live-demo',
  TIME_ZONE: 'America/New_York',
  DEFAULT_STAGES: [
    'Lead',
    '30% Committed',
    '60% Committed',
    '90% Committed',
    'Application',
    'Submitted',
  ],
  SMS_CREDIT: [
    {
      PRICE: 600,
      AMOUNT: 250,
    },
    {
      PRICE: 1000,
      AMOUNT: 500,
    },
    {
      PRICE: 1500,
      AMOUNT: 1000,
    },
  ],
  DIALER_FREE_TRIAL: 14,
  REFERRAL_DEEP: 3,
  USER_VERSION: 2.3,
  REPLACE_NAME: 'crmgrow',
  PACKAGE_LEVEL: [0, 29, 49, 99],
  MLM_LEVEL: [0, 0.1, 0.15, 0.12],
  PRO_CODE: {
    EVO: 'QWERAS',
  },
  OFFER: {
    ONE_MONTH_TRIAL: '1 free subscription months',
    TWENTY_PERCENT_DISCOUNT: '20% discount coupon',
  },
  AGENT: {
    LAST_LOGGEDIN: 7,
    SERVICE_PASSWORD: process.env.AGENT_SERVICE_PASSWORD,
    SERVICE_API: process.env.AGENT_SERVICE_API,
  },
  ROUND_ROBIN_CURSOR_EXPIRE: 1,
  GMAIL_WATCH_EXPIRE: 5,
  DEFAULT_REDX_COMMUNITY_ID: '64d118df44972de0cbc2dc3d',
};

module.exports = system_settings;
