const canned_message = [
  'my_name',
  'my_email',
  'my_phone',
  'contact_first_name',
  'contact_last_name',
  'contact_email',
  'contact_phone',
  'video_title',
  'video_link',
  'video_description',
  'video_object',
  'pdf_title',
  'pdf_description',
  'pdf_object',
];
const templateTokens = [
  {
    id: 1,
    name: 'contact_first_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 2,
    name: 'contact_last_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 3,
    name: 'contact_email',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 4,
    name: 'contact_phone',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 5,
    name: 'my_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 6,
    name: 'my_first_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 7,
    name: 'my_email',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 8,
    name: 'my_phone',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 9,
    name: 'my_company',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 10,
    name: 'assignee_first_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 11,
    name: 'assignee_last_name',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 12,
    name: 'assignee_email',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 13,
    name: 'assignee_phone',
    value: '',
    match_field: '',
    default: true,
  },
  {
    id: 14,
    name: 'scheduled_time',
    value: '',
    match_field: '',
    default: true,
  },
];

module.exports = canned_message;
module.exports.templateTokens = templateTokens;
