const time_zone = {
  '-04:00': 'America/Anguilla',
  '-05:00': 'America/Cancun',
  '-06:00': 'America/Belize',
  '-07:00': 'America/Phoenix',
  '-08:00': 'America/Los_Angeles',
  '-09:00': 'America/Anchorage',
  '-10:00': 'America/Atka',
};

const days = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];

const lead_caputure_countries = [
  { label: 'United States', name: 'US' },
  { label: 'Canada', name: 'CA' },
];

const lead_capture_regions = {
  US: [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Palau',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'District of Columbia',
  ],
  CA: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
  ],
};

const country_state = [
  {
    name: 'US',
    state: {
      AL: 'Alabama',
      AK: 'Alaska',
      AS: 'American Samoa',
      AZ: 'Arizona',
      AR: 'Arkansas',
      CA: 'California',
      CO: 'Colorado',
      CT: 'Connecticut',
      DE: 'Delaware',
      DC: 'District Of Columbia',
      FM: 'Federated States Of Micronesia',
      FL: 'Florida',
      GA: 'Georgia',
      GU: 'Guam',
      HI: 'Hawaii',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      IA: 'Iowa',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiana',
      ME: 'Maine',
      MH: 'Marshall Islands',
      MD: 'Maryland',
      MA: 'Massachusetts',
      MI: 'Michigan',
      MN: 'Minnesota',
      MS: 'Mississippi',
      MO: 'Missouri',
      MT: 'Montana',
      NE: 'Nebraska',
      NV: 'Nevada',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'New Mexico',
      NY: 'New York',
      NC: 'North Carolina',
      ND: 'North Dakota',
      MP: 'Northern Mariana Islands',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PW: 'Palau',
      PA: 'Pennsylvania',
      PR: 'Puerto Rico',
      RI: 'Rhode Island',
      SC: 'South Carolina',
      SD: 'South Dakota',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VT: 'Vermont',
      VI: 'Virgin Islands',
      VA: 'Virginia',
      WA: 'Washington',
      WV: 'West Virginia',
      WI: 'Wisconsin',
      WY: 'Wyoming',
    },
  },
  {
    name: 'CA',
    state: {
      AB: 'Alberta',
      BC: 'British Columbia',
      MB: 'Manitoba',
      NB: 'New Brunswick',
      NF: 'Newfoundland',
      NT: 'Northwest Territories',
      NS: 'Nova Scotia',
      NU: 'Nunavut',
      ON: 'Ontario',
      PE: 'Prince Edward Island',
      PQ: 'Quebec',
      SK: 'Saskatchewan',
      YT: 'Yukon',
    },
  },
  {
    name: 'AU',
    state: {
      NSW: 'New South Wales',
      VIC: 'Victoria',
      QLD: 'Queensland',
      TAS: 'Tasmania',
      SA: 'South Australia',
      WA: 'Western Australia',
      NT: 'Northern Territory',
      ACT: 'Australian Capital Territory',
    },
  },
  {
    name: 'DE',
    state: {
      BW: 'Baden-Württemberg',
      BY: 'Bavaria',
      BE: 'Berlin',
      BB: 'Brandenburg',
      HB: 'Bremen',
      HH: 'Hamburg',
      HE: 'Hesse',
      NI: 'Lower Saxony',
      MV: 'Mecklenburg-Vorpommern',
      NW: 'North Rhine-Westphalia',
      RP: 'Rhineland-Palatinate',
      SL: 'Saarland',
      SN: 'Saxony',
      ST: 'Saxony-Anhalt',
      SH: 'Schleswig-Holstein',
      TH: 'Thuringia',
    },
  },
  {
    name: 'IN',
    state: {
      AP: 'Andhra Pradesh',
      AR: 'Arunachal Pradesh',
      AS: 'Assam',
      BR: 'Bihar',
      CT: 'Chhattisgarh',
      GA: 'Goa',
      GJ: 'Gujarat',
      HR: 'Haryana',
      HP: 'Himachal Pradesh',
      JH: 'Jharkhand',
      KA: 'Karnataka',
      KL: 'Kerala',
      MP: 'Madhya Pradesh',
      MH: 'Maharashtra',
      MN: 'Manipur',
      ML: 'Meghalaya',
      MZ: 'Mizoram',
      NL: 'Nagaland',
      OR: 'Odisha',
      PB: 'Punjab',
      RJ: 'Rajasthan',
      SK: 'Sikkim',
      TN: 'Tamil Nadu',
      TG: 'Telangana',
      TR: 'Tripura',
      UP: 'Uttar Pradesh',
      UT: 'Uttarakhand',
      WB: 'West Bengal',
    },
  },
  {
    name: 'MX',
    state: {
      AG: 'Aguascalientes',
      BC: 'Baja California',
      BS: 'Baja California Sur',
      CH: 'Chihuahua',
      CL: 'Colima',
      CM: 'Campeche',
      CO: 'Coahuila',
      CS: 'Chiapas',
      DF: 'Federal District',
      DG: 'Durango',
      GR: 'Guerrero',
      GT: 'Guanajuato',
      HG: 'Hidalgo',
      JA: 'Jalisco',
      ME: 'México State',
      MI: 'Michoacán',
      MO: 'Morelos',
      NA: 'Nayarit',
      NL: 'Nuevo León',
      OA: 'Oaxaca',
      PB: 'Puebla',
      QE: 'Querétaro',
      QR: 'Quintana Roo',
      SI: 'Sinaloa',
      SL: 'San Luis Potosí',
      SO: 'Sonora',
      TB: 'Tabasco',
      TL: 'Tlaxcala',
      TM: 'Tamaulipas',
      VE: 'Veracruz',
      YU: 'Yucatán',
      ZA: 'Zacatecas',
    },
  },
  {
    name: 'ZA',
    state: {
      EC: 'Eastern Cape',
      FS: 'Free State',
      GT: 'Gauteng',
      NL: 'KwaZulu-Natal',
      LP: 'Limpopo',
      MP: 'Mpumalanga',
      NC: 'Northern Cape',
      NW: 'North West',
      WC: 'Western Cape',
    },
  },
  {
    name: 'UK',
    state: {
      ENGLAND: 'England',
      'NORTHERN IRELAND': 'Northern Ireland',
      SCOTLAND: 'Scotland',
      WALES: 'Wales',
    },
  },
];

var country = {};

const country_state1 = [];

const countries = require('country-state-city').Country;
const countryStates = require('country-state-city').State;

const all_countries = countries.getAllCountries();

const outbound_constants = {
  ADD_CONTACT: 'add_contact',
  UPDATE_CONTACT: 'update_contact',
  DELETE_CONTACT: 'delete_contact',
  ADD_DEAL: 'add_deal',
  MOVE_DEAL: 'move_deal',
  SEND_MATERIAL: 'send_material',
  WATCH_MATERIAL: 'watch_material',
  ASSINGED_AUTOMATION: 'assigned_automation',
  CREATE_NOTE: 'create_note',
  UPDATE_NOTE: 'update_note',
  DELETE_NOTE: 'delete_note',
  CREATE_TASK: 'create_task',
  UPDATE_TASK: 'update_task',
  DELETE_TASK: 'delete_task',
  LEAD_SOURCE: 'lead_source',
};

const inbound_constants = {
  ADD_CONTACT: 'add_contact',
  UPDATE_CONTACT: 'update_contact',
  CREATE_FOLLOWUP: 'create_followup',
  ADD_NOTE: 'add_note',
  ASSING_AUTOMATION: 'assign_automation',
  ADD_TAG: 'add_tag',
  SEND_VIDEO: 'send_video',
  SEND_PDF: 'send_pdf',
  SEND_IMAGE: 'send_image',
};

const country_codes = () => {
  for (let i = 0; i < all_countries.length; i++) {
    country[all_countries[i].name] = all_countries[i].isoCode;
    // const state = {};
    // state['name'] = all_countries[i].isoCode;
    // const tempStates = countryStates.getStatesOfCountry(
    //   all_countries[i].isoCode
    // );
    // const statelists = {};

    // if (tempStates && tempStates.length > 0) {
    //   for (let j = 0; j < tempStates.length; j++) {
    //     statelists[tempStates[j].isoCode] = tempStates[j].name;
    //   }
    // }

    // state['state'] = { ...statelists };
    // country_state1.push(state);
  }
};

const all_time_zones = {
  'America/Los_Angeles': 'Pacific Standard Time',
  'America/Denver': 'Mountain Standard Time',
  'America/Chicago': 'Central Standard Time',
  'America/New_York': 'Eastern Standard Time',
  'America/Halifax': 'Atlantic Standard Time',
  'America/Phoenix': 'Arizona, Yukon Time',
  'America/Anchorage': 'Alaska Daylight Time',
  'America/St_Johns': 'Newfoundland Standard Time',
  'Pacific/Honolulu': 'Hawaii Standard Time',
};

const material_themes = [
  'theme2',
  'theme3',
  'theme4',
  'theme6',
  'theme7',
  'theme8',
];
const TIME_ZONE_NAMES = {
  'America/Los_Angeles': 'Pacific Time',
  'America/Denver': 'Mountain Time',
  'America/Chicago': 'Central Time',
  'America/New_York': 'Eastern Time',
  'America/Halifax': 'Atlantic Time',
  'America/Indiana/Marengo': 'Indiana (East) Time',
  'America/Phoenix': 'Arizona, Yukon Time',
  'America/Anchorage': 'Alaska Time',
  'Pacific/Honolulu': 'Hawaii Time',
  'America/St_Johns': 'Newfoundland Time',
  'America/Honolulu': 'Hawaii Time',
  'America/Argentina/La_Rioja': 'Argentina Time',
  'America/Asuncion': 'Paraguay Time',
  'America/Bogota': 'SA Pacific Time',
  'America/Campo_Grande': 'Central Brazilian Time',
  'America/Caracas': 'Venezuela Time',
  'America/Godthab': 'Greenland Time',
  'America/Belize': 'Central America Time',
  'America/Detroit': 'Eastern Time',
  'America/Chihuahua': 'Mountain Time (Mexico)',
  'America/Santa_Isabel': 'Pacific Time (Mexico)',
  'America/Regina': 'Canada Central Time',
  'America/Bahia_Banderas': 'Central Time (Mexico)',
  'America/Miquelon': 'America/Miquelon',
  'America/Noronha': 'America/Noronha',
  'America/Sao_Paulo': 'E. South America Time',
  'America/Anguilla': 'SA Western Time',
  'America/Santiago': 'Pacific SA Time',
  'America/Araguaina': 'SA Eastern Time',
  'America/Bahia': 'Bahia Time',
  'America/Montevideo': 'Montevideo Time',
  'Asia/Amman': 'Jordan Time',
  'Asia/Baghdad': 'Arabic Time',
  'Asia/Baku': 'Azerbaijan Time',
  'Asia/Damascus': 'Syria Time',
  'Asia/Dhaka': 'Bangladesh Time',
  'Asia/Dubai': 'Arabian Time',
  'Asia/Kuwait': 'Arab Time',
  'Antarctica/Davis': 'SE Asia Time',
  'Asia/Jerusalem': 'Israel Time',
  'Asia/Tehran': 'Iran Time',
  'Asia/Kabul': 'Afghanistan Time',
  'Asia/Yekaterinburg': 'Yekaterinburg Time',
  'Pacific/Majuro': 'Pacific/Majuro',
  'Asia/Karachi': 'Pakistan Time',
  'Asia/Kolkata': 'India Time',
  'Asia/Colombo': 'Sri Lanka Time',
  'Asia/Kathmandu': 'Nepal Time',
  'Asia/Bishkek': 'Central Asia Time',
  'Asia/Rangoon': 'Myanmar Time',
  'Asia/Bangkok': 'SE Asia Time',
  'Asia/Novokuznetsk': 'N. Central Asia Time',
  'Asia/Shanghai': 'China, Singapore Time',
  'Asia/Irkutsk': 'North Asia Time',
  'Asia/Tokyo': 'Japan Time',
  'Asia/Pyongyang': 'Korea Time',
  'Asia/Chita': 'Yakutsk Time',
  'Asia/Yerevan': 'Caucasus Time',
  'Asia/Vladivostok': 'Vladivostok Time',
  'Asia/Kamchatka': 'Kamchatka Time',
  'Asia/Belgrade': 'Central Europe Time',
  'Asia/Nicosia': 'East Europe Time',
  'Asia/Madrid': 'Romance Time',
  'Atlantic/Canary': 'GMT Time',
  'Europe/Helsinki': 'Helsinki, Kyiv Time',
  'Europe/Moscow': 'Moscow Time',
  'Europe/Astrakhan': 'Samara Time',
  'Europe/Berlin': 'W. Europe Time',
  'Europe/Istanbul': 'Turkey Time',
  'Africa/Cairo': 'Egypt Time',
  'Africa/Algiers': 'W. Central Africa Time',
  'Africa/Windhoek': 'Namibia Time',
  'Africa/Blantyre': 'South Africa Time',
  'Africa/Tripoli': 'Libya Time',
  'Africa/Addis_Ababa': 'E. Africa Time',
  'Africa/Casablanca': 'Morocco Time',
  'Africa/Abidjan': 'Monrovia, Reykjavik',
  'America/Scoresbysund': 'Azores Time',
  'Atlantic/Cape_Verde': 'Cape Verde Time',
  'Australia/Adelaide': 'Cen. Australia Time',
  'Australia/Brisbane': 'E. Australia Time',
  'Australia/Darwin': 'AUS Central Time',
  'Australia/Currie': 'Tasmania Time',
  'Australia/Melbourne': 'AUS Eastern Time',
  'Pacific/Efate': 'Central Pacific Time',
  'Pacific/Auckland': 'New Zealand Time',
  'Pacific/Apia': 'Samoa Standard Time',
  'Pacific/Chatham': 'Pacific/Chatham',
  'Pacific/Easter': 'Pacific/Easter',
  'Pacific/Fiji': 'Fiji Time',
  'Pacific/Gambier': 'Gambier Island Time',
  'Pacific/Kiritimati': 'Pacific/Kiritimati',
  'Pacific/Marquesas': 'Marquesas Time',
  'Pacific/Norfolk': 'Norfolk Island',
  'Pacific/Pitcairn': 'Pitcairn Time',
  'Pacific/Enderbury': 'Tonga Time',
  'Europe/Belgrade': 'Central Europe Time',
  'Europe/Madrid': 'Romance Time',
  'Etc/GMT': 'UTC',
};
const DISABLE_NEXT_MODE = {
  default: 'default',
  invalid: 'invalid-action',
};
module.exports.time_zone = time_zone;
module.exports.days = days;
module.exports.country_codes = country_codes;
module.exports.CountryState = country_state;
module.exports.Countries = country;
module.exports.lead_caputure_countries = lead_caputure_countries;
module.exports.lead_capture_regions = lead_capture_regions;
module.exports.outbound_constants = outbound_constants;
module.exports.all_time_zones = all_time_zones;
module.exports.inbound_constants = inbound_constants;
module.exports.material_themes = material_themes;
module.exports.TIME_ZONE_NAMES = TIME_ZONE_NAMES;
module.exports.DISABLE_NEXT_MODE = DISABLE_NEXT_MODE;
