get:
  tags: [ Inbound APIs ]
  summary: Get automations
  description: |
    Get automations
  security:
    - crmgAuthorization: []
 
  responses:
    '200':
      description: crmgrow log in successfully
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AutomationModel'